version: "3"

dotenv:
  - .env
  - .env.default

output: prefixed

tasks:
  # |------------------------------------------------------------------------------------------------------------------
  # | Tools
  # |------------------------------------------------------------------------------------------------------------------
  tools:
    desc: Install tools to ./tools directory
    deps:
      - tools:go-licenses
      - tools:golangci-lint
      - tools:rancher-machine
    silent: true
    cmd: >
      echo "✅ ALL TOOLS INSTALLED"

  tools:go-licenses:
    vars:
      VERSION: v1.6.0
    cmd: >
      mkdir -p ./tools
      && export GOBIN="$(realpath ./tools)"
      && go install github.com/google/go-licenses@{{.VERSION}}

  tools:golangci-lint:
    vars:
      VERSION: v1.64.6
    status:
      - >
        ./tools/golangci-lint version --format short
        | grep -q '{{.VERSION}}'
    cmd: >
      mkdir -p ./tools
      && export GOBIN="$(realpath ./tools)"
      && go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.VERSION}}

  tools:rancher-machine:
    vars:
      VERSION: v0.15.0-rancher126
    status:
      - >
        ./tools/rancher-machine --version
        | grep -q '{{.VERSION}}'
    cmd: >
      mkdir -p ./tools
      && curl -L https://github.com/rancher/machine/releases/download/{{.VERSION}}/rancher-machine-amd64.tar.gz
      | tar -xvzf - -C ./tools

  # |------------------------------------------------------------------------------------------------------------------
  # | Dependencies
  # |------------------------------------------------------------------------------------------------------------------
  dependencies:
    desc: Install dependencies
    deps:
      - dependencies:node
      - dependencies:go
    silent: true
    cmd: >
      echo "✅ ALL DEPENDENCIES INSTALLED"

  dependencies:node:
    method: checksum
    sources:
      - package.json
      - yarn.lock
    cmd: >
      yarn install --frozen-lockfile

  dependencies:go:
    method: checksum
    sources:
      - go.mod
      - go.sum
    cmds:
      - go mod tidy
      - go mod vendor

  # |------------------------------------------------------------------------------------------------------------------
  # | Linters (&checks)
  # |------------------------------------------------------------------------------------------------------------------
  lint:
    desc: Run linters
    deps:
      - lint:commits
      - lint:go
      - lint:go-licenses
      - lint:markdown
    silent: true
    cmd: >
      echo "✅ ALL LINTERS PASSED"

  lint:commits:
    deps:
      - dependencies:node
    cmd: >
      yarn exec commitlint -- --from=main --verbose

  lint:go:
    deps:
      - tools:golangci-lint
      - dependencies:go
    cmd: >
      ./tools/golangci-lint run -v

  lint:go-licenses:
    deps:
      - tools:go-licenses
      - dependencies:go
    cmd: >
      ./tools/go-licenses check ./...
      --ignore "github.com/stellatarum/docker-machine-driver-pve"
      --disallowed_types=forbidden,restricted,reciprocal,unknown

  lint:markdown:
    deps:
      - dependencies:node
    cmd: >
      yarn exec markdownlint-cli2 -- **/*.md

  # |------------------------------------------------------------------------------------------------------------------
  # | Builds
  # |------------------------------------------------------------------------------------------------------------------
  build:
    desc: Build project
    deps:
      - build:docker-machine-driver-pve
    silent: true
    cmd: >
      echo "✅ PROJECT BUILT"

  build:docker-machine-driver-pve:
    deps:
      - dependencies:go
    sources:
      - cmd/**/*.go
    cmd: >
      mkdir -p ./bin
      && CGO_ENABLED="0" go build -o ./bin/docker-machine-driver-pve ./cmd/docker-machine-driver-pve
