apiVersion: v2
type: application
version: "0.0.0-devel"
appVersion: "0.0.0-devel"
name: pve-node-driver
description: Node Driver for Proxmox Virtual Environment.
home: https://github.com/stellatarum/docker-machine-driver-pve
sources:
  - https://github.com/stellatarum/docker-machine-driver-pve
maintainers:
  - name: Stellatarum
    email: contact@stellatarum.com
    url: https://stellatarum.com/
keywords:
  - infrastructure
annotations:
  # See: https://documentation.suse.com/cloudnative/rancher-manager/latest/en/cluster-admin/helm-charts-in-rancher/create-apps.html#_chart_yaml_annotations
  catalog.cattle.io/display-name: Proxmox VE Node Driver
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/release-name: pve-node-driver
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/kube-version: ">= 1.16.0-0"
  catalog.cattle.io/rancher-version: ">= 2.10.0-0"
  catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
