apiVersion: management.cattle.io/v3
kind: NodeDriver
metadata:
  name: pve
  labels:
    app.kubernetes.io/name: pve-node-driver
    app.kubernetes.io/version: {{ trimPrefix "v" .Chart.AppVersion | quote }}
  annotations:
    publicCredentialFields: url,insecureTls,tokenId
    privateCredentialFields: tokenSecret
    optionalCredentialFields: insecureTls
    passwordFields: tokenSecret
spec:
  displayName: "Proxmox VE"
  description: "Node Driver for Proxmox Virtual Environment"
  uiUrl: ""
  url: {{ .Values.nodeDriver.url | quote }}
  checksum: {{ .Values.nodeDriver.checksum | quote }}
  externalId: ""
  active: true
  addCloudCredential: true
  builtin: false
